title: "[💌 HELP] "
labels: ["Ask the community for help."]
body:
  - type: textarea
    attributes:
      label: Summary
      description: What do you need help with?
      placeholder: "I need help with ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Any code snippets, error messages, or dependency details that may be related?
      placeholder: "This is a bug in ..."
      render: js
    validations:
      required: false
  - type: input
    attributes:
      label: Example
      description: A link to a minimal reproduction is helpful for collaborative debugging!
      placeholder: "https://codesandbox.io/s/..."
    validations:
      required: false
