blank_issues_enabled: true
contact_links:
  - name: Author's Telegram
    url: https://t.me/hoangnhan2ka3
    about: Please DM me if you have any questions.
  - name: Author's Gmail
    url: mailto:workwith.hnhan@gmail.com
    about: Please send me an email if you have any questions.
