name: Release

permissions:
    contents: write

on:
    push:
        tags:
            - v[0-9]+.[0-9]+.*

defaults:
    run:
        shell: bash

jobs:
    create-release:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: taiki-e/checkout-action@v1
            - uses: taiki-e/create-gh-release-action@v1
              with:
                    changelog: CHANGELOG.md
                    draft: true
                    title: $tag
                    branch: 'main|v[0-9]+'
                    token: ${{ secrets.GITHUB_TOKEN }}
